### PR TITLE
JSON Guide

### PR DESCRIPTION
**Pull request by timsehn**

### CODE REVIEW

**Comment by timsehn** [comment]
Is this better as a blog?

**Review by andy-wm-arthur — APPROVED** [review]
LGTM, I might add a mention for [JSON path](https://docs.oracle.com/cd/E60058_01/PDF/8.0.8.x/8.0.8.0.0/PMF_HTML/JsonPath_Expressions.htm) syntax

**Comment by timsehn** [comment]
> LGTM, I might add a mention for [JSON path](https://docs.oracle.com/cd/E60058_01/PDF/8.0.8.x/8.0.8.0.0/PMF_HTML/JsonPath_Expressions.htm) syntax

Done in latest. Good feedback.

**Comment by timsehn** [comment]
Made this a blog instead.

**Pull request closed without merging**
